### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by merdj** [huang-x-h/sidebar-menu#2]
hi, 

your sidebar-menu is great, can you include please RTL? and it will display as well in right not only on left?

thanks

**Comment by huang-x-h** [comment]
do you mean place the sidebar-menu on right?

**Comment by merdj** [comment]
yes, it will at the right at the same time li's will be right to left. this will support hebrew, arabic and other RTL languages. i was able to make it move to right (body {direction:rtl}) and also, text of li's also moved using text-align:right, even the icons for submenu moved trom ltr to rtl. but my problem is the icons for non-submenu, it is not good.

thank you

**Comment by huang-x-h** [comment]
you can change template icons class `pull-right` to `pull-left`

**Comment by merdj** [comment]
![image](https://cloud.githubusercontent.com/assets/1001881/20660503/054a5396-b55b-11e6-830f-a594e251e8dd.png)

see the attached screenshot, perhaps it could help. the more the submenu getting deeper the li's are getting narrower.

from the original:

![image](https://cloud.githubusercontent.com/assets/1001881/20661165/5ae85368-b55e-11e6-8f3d-f4aabecdbb01.png)

thank you

**Comment by huang-x-h** [comment]
add `sidebar-menu-rtl` class for `rtl` direction, use `sidebar-menu-rtl` instead of `sidebar-menu`, and also you should change arrow class `pull-right` to `pull-left`

rtl examples see [index-rtl.html](https://github.com/huang-x-h/sidebar-menu/blob/master/index-rtl.html)

**Comment by merdj** [comment]
hi, works perfectly now, thank you so much

**Comment by huang-x-h** [comment]
ok. fixed
