### ISSUE TITLE
hamburger

### ISSUE THREAD

**Issue by merdj** [huang-x-h/sidebar-menu#3]
hello,

how about increasing the feature such as having a hamburger part of header menu? where in when a user click the hamburger it will show the sidebar-menu and hide once any area outside the menu will hide it? also the hamburger can be placed either left or right?

just a suggestion.

thank you

see the below link as an example:
http://www.jqueryscript.net/demo/Mobile-First-Hamburger-Menu-Plugin-For-jQuery/

**Comment by huang-x-h** [comment]
Just like a mini sidebar-menu or hide sidebar-menu?

If you need click the hamburger button to slide in/out the sidebar-menu, you can see `slideout` component which earlier i wrote, it's not independence.

- `css` https://github.com/huang-x-h/Bean.js/blob/master/scss/slideout.scss
- `js` https://github.com/huang-x-h/Bean.js/blob/master/src/components/slideout.js
- `html` https://github.com/huang-x-h/Bean.js/blob/master/build/examples/slideout/index.html

Or if you need click the hamburger button to show mini sidebar-menu, maybe i will fixed later see #1

**Comment by merdj** [comment]
hi,
 
thank you for your reply.

the sample you have shown have a missing css file. (main.css). kindly provide it please and let me explore your components,

thank you

**Comment by huang-x-h** [comment]
You just compile `slideout.scss` and import in html file, the [`main.css`](https://github.com/huang-x-h/Bean.js/blob/master/scss/main.scss) include all components css file.

If you explore the component independency, the js file should rewrite (it was wrote like a jquery ui component)

**Comment by huang-x-h** [comment]
Now, we add `animate` to Sidebar Menu, so you can show/hide the menu, update and try it.

Thanks
