### ISSUE TITLE
Collapsed 

### ISSUE THREAD

**Issue by mehrdadch** [huang-x-h/sidebar-menu#4]
how sidebar Collapsed

**Comment by huang-x-h** [comment]
Do you mean hide sidebar like #3 ？

**Comment by melloware** [comment]
This menu looks great but I agree with all 3 issues the one thing you are missing is the ability to hide the menu. Like in this demo here:  http://www.primefaces.org/atlantis/

**Comment by huang-x-h** [comment]
see #3
