### ISSUE TITLE
Could you add LICENSE file?

### ISSUE THREAD

**Issue by BlueSkyDetector** [huang-x-h/sidebar-menu#6]
Though I could find MIT license setting in "package.json", it's not easy to find and github is suggesting to include the license file.
https://help.github.com/articles/licensing-a-repository/

And "sidebar-menu" is based on "AdminLTE", so copyright notice and permission notice of "AdminLTE" are also needed to be included.
It's required.
Please check following lines in "AdminLTE" license file.

```
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
```
https://github.com/almasaeed2010/AdminLTE/blob/master/LICENSE

You can reference following URL for including copyright notice and permission notice.
https://opensource.stackexchange.com/questions/5484/how-to-use-mit-license-in-a-project#answer-5488

I'm sorry if you feel I'm pointing too much in detail, but I'd like to use "sidebar-menu" in better legal status.

**Comment by huang-x-h** [comment]
@BlueSkyDetector Thanks for your advise. `LICENSE` file is add.

This component just inspire of the AdminLTE, add some different feature, so maybe we do not need include

Also `AdminLTE` is base no `bootstrap`, the license do not include `bootstrap` license.

**Comment by BlueSkyDetector** [comment]
Thank you. :+1:
