### ISSUE TITLE
Menu collapses on page load

### ISSUE THREAD

**Issue by mfkashani** [huang-x-h/sidebar-menu#8]
How can the menu not keep its collapse/expanded state on page load? Not practical as is.

**Comment by huang-x-h** [comment]
Hi, you can trigger the menu expanded by manual.

For example

```html
<a data-label="dashboard" href="#">
  <i class="fa fa-dashboard"></i> <span>Dashboard</span> <i class="fa fa-angle-left pull-right"></i>
</a>
```

```js
$('a[data-label="dashboard"]').trigger('click')
```

**Comment by mfkashani** [comment]
Thank you.
So, if I am on the home page and click "Dashboard" and load the dashboard
page, I then have to trigger another click action in order to have the menu
expanded and showing "Dashboard" selected, in effect loading the dashboard
page twice, correct?

**Comment by huang-x-h** [comment]
yes, you can store the click menu on browser localStorage, so load the page you can known the click menu :)
